version: "3.9"

services:

  flarum:
    build: .
    container_name: flarum
    restart: unless-stopped
    env_file:
      - ./flarum.env
    volumes:
      - ./flarumapp:/flarum/app
      - ./flarumnginx:/etc/nginx/flarum
    expose:
      - 8888
    depends_on:
      - mariadb
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nginx-proxy"

      - "traefik.http.routers.flarum-http.entrypoints=http"
      - "traefik.http.routers.flarum-http.rule=Host(`<your domain>`)"
      - "traefik.http.routers.flarum-http.middlewares=https-redirect@file"
      - "traefik.http.routers.flarum-http.service=noop@file"

      - "traefik.http.routers.flarum-https.entrypoints=https"
      - "traefik.http.routers.flarum-https.rule=Host(`<your domain>`)"
      - "traefik.http.routers.flarum-https.middlewares=content-compress@file"
      - "traefik.http.routers.flarum-https.service=flarum-backend"
      - "traefik.http.routers.flarum-https.tls=true"
      - "traefik.http.routers.flarum-https.tls.certresolver=<your certresolver>"

      - "traefik.http.services.flarum-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.flarum-backend.loadbalancer.server.port=8888"

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=<your password>
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=<your password>
    volumes:
      - ./mysql/db:/var/lib/mysql
    networks:
      - default

networks:
  default:
    name: nginx-proxy
    external: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
